name: Github pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Yarn install
        run: yarn
      - name: Yarn build
        run: yarn build

      - name: Release pages
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          # Build directory to deploy
          build_dir: dist
          # The committer name and email address
          committer: github-actions[bot]@users.noreply.github.com
          # The author name and email address
          author: github-actions[bot]
          # Commit message
          commit_message: Update pages
